# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Database
  licenses: Apache-2.0
  images: |
    - name: kubectl
      image: docker.io/bitnamilegacy/kubectl:1.29.3-debian-12-r3
    - name: mongodb
      image: docker.io/bitnamilegacy/mongodb:7.0.8-debian-12-r2
    - name: mongodb-exporter
      image: docker.io/bitnamilegacy/mongodb-exporter:0.40.0-debian-12-r15
    - name: nginx
      image: docker.io/bitnamilegacy/nginx:1.25.4-debian-12-r7
    - name: os-shell
      image: docker.io/bitnamilegacy/os-shell:12-debian-12-r18
apiVersion: v2
appVersion: 7.0.8
dependencies:
- name: common
  repository: oci://ghcr.io/cowboysysop/charts
  tags:
  - bitnami-common
  version: 2.31.3
description: MongoDB(R) is a relational open source NoSQL database. Easy to use, it stores data in JSON-like documents. Automated scalability and high-performance. Ideal for developing cloud native applications.
home: https://github.com/cowboysysop/charts/tree/master/charts/mongodb
icon: https://raw.githubusercontent.com/cowboysysop/charts/master/charts/mongodb/icon.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: sebastien-prudhomme
  email: sebastien.prudhomme@gmail.com
name: mongodb
sources:
- https://github.com/cowboysysop/charts/tree/master/charts/mongodb
version: 16.0.0
