{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-mcp.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "grafana-mcp.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  grafana-api-key: {{ .Values.grafana.apiKey | b64enc | quote }}
{{- end }}
