apiVersion: v1
kind: Service
metadata:
  name: {{ include "qdrant.headless.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "qdrant.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.headless.service.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.headless.service.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  {{- if .Values.headless.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.headless.service.ipFamilyPolicy }}
  {{- end }}
  {{- if not (empty .Values.headless.service.ipFamilies)}}
  ipFamilies: {{- toYaml .Values.headless.service.ipFamilies | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.headless.service.ports.p2p }}
      targetPort: tcp-p2p
      protocol: TCP
      name: tcp-p2p
  publishNotReadyAddresses: true
  selector:
    {{- include "qdrant.selectorLabels" . | nindent 4 }}
