apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lighthouse-ci.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "lighthouse-ci.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  lighthouserc.json: |
    {
      "ci": {
        "server": {
          "port": {{ .Values.containerPorts.http }},
          "storage": {
            "storageMethod": "sql",
            "sqlDialect": "sqlite",
            "sqlDatabasePath": "/data/lhci.db"
          },
          "psiCollectCron": {
            "psiApiKey": {{ .Values.psiCollectCron.psiApiKey | quote }},
            "sites": {{ .Values.psiCollectCron.sites | toJson }}
          },
          "deleteOldBuildsCron": {{ .Values.deleteOldBuildsCron | toJson }}
        }
      }
    }
